# 0.0 Planejamento

O exercício consiste em avaliar a performance de diferentes algoritmos. Para isso é necessário testar diferentes parâmetros e olhar diferentes métricas.
* Dividir entre Classificação, Regressão e Clusterização
* Começar testando empiricamente

# 0.1 Imports

In [14]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics as mt
from sklearn import tree as tr
from sklearn import ensemble as en
from sklearn import linear_model as lm

In [2]:
# Load dataset
pd.set_option('display.max_columns', None)
X_train = pd.read_csv('X_training.csv')

X_train.head()

,id,customer_type,age,class,flight_distance,inflight_wifi_service,departure_arrival_time_convenient,ease_of_online_booking,gate_location,food_and_drink,online_boarding,seat_comfort,inflight_entertainment,on_board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,gender_Female,gender_Male,type_of_travel_business_travel,type_of_travel_personal_travel
0,13508,1,0.500000,0.0,0.039580,0.6,0.6,0.6,0.6,1.0,1.0,0.25,0.6,0.6,0.6,0.5,1.00,0.6,0.4,0.000000,0.013848,1.0,0.0,1.0,0.0
1,28874,1,0.243590,0.0,0.205775,0.6,0.4,0.4,0.4,0.6,0.8,0.50,0.6,0.4,0.8,0.5,0.50,0.2,0.6,0.000000,0.000000,0.0,1.0,1.0,0.0
2,21484,0,0.435897,1.0,0.026858,0.6,0.6,0.6,0.2,1.0,0.6,1.00,1.0,0.4,0.4,0.0,1.00,0.6,1.0,0.000000,0.000000,1.0,0.0,1.0,0.0
3,48280,1,0.589744,0.5,0.041397,0.6,1.0,0.6,0.6,0.8,1.0,0.00,0.4,0.4,0.6,0.0,1.00,0.4,0.4,0.029499,0.020772,1.0,0.0,0.0,1.0
4,472,0,0.423077,1.0,0.016559,0.2,0.2,0.2,0.8,0.6,0.2,0.50,0.6,1.0,0.6,1.0,0.75,0.8,0.6,0.021632,0.019782,0.0,1.0,1.0,0.0

In [3]:
# removendo id
X_train = X_train.drop(X_train.columns[0], axis=1)
X_train.head(1)

,customer_type,age,class,flight_distance,inflight_wifi_service,departure_arrival_time_convenient,ease_of_online_booking,gate_location,food_and_drink,online_boarding,seat_comfort,inflight_entertainment,on_board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,gender_Female,gender_Male,type_of_travel_business_travel,type_of_travel_personal_travel
0,1,0.5,0.0,0.03958,0.6,0.6,0.6,0.6,1.0,1.0,0.25,0.6,0.6,0.6,0.5,1.0,0.6,0.4,0.0,0.013848,1.0,0.0,1.0,0.0

In [4]:
X_train.shape

(72515, 24)

In [5]:
X_train_s = X_train.sample(frac=0.1, random_state=0)
X_train_s.shape

(7252, 24)

In [6]:
y_train = pd.read_csv('y_training.csv')

y_train= np.ravel(y_train)
y_train.shape

(72515,)

In [7]:
y_train_s = y_train[X_train_s.index]
y_train_s.shape

(7252,)

In [8]:
#X_val
X_val = pd.read_csv('X_validation.csv')
X_val_s = X_val.sample(frac=0.1, random_state=0)
X_val_s.shape

(3108, 25)

In [9]:
#removendo id
X_val_s = X_val_s.drop(X_val_s.columns[0], axis=1)
X_val_s.head(1)

,customer_type,age,class,flight_distance,inflight_wifi_service,departure_arrival_time_convenient,ease_of_online_booking,gate_location,food_and_drink,online_boarding,seat_comfort,inflight_entertainment,on_board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,gender_Female,gender_Male,type_of_travel_business_travel,type_of_travel_personal_travel
9328,1,0.435897,1.0,0.176898,0.6,0.6,0.6,0.6,0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [10]:
# y_val
y_val = pd.read_csv('y_validation.csv')
y_val = np.ravel(y_val)
y_val_s = y_val[X_val_s.index]
y_val_s.shape

(3108,)

In [11]:
#X_test
X_test = pd.read_csv('X_test.csv')
X_test_s = X_test.sample(frac=0.1, random_state=0)
X_test_s.shape

X_test_s = X_test_s.drop(X_test_s.columns[0], axis=1)
X_test_s.head(1)

,customer_type,age,class,flight_distance,inflight_wifi_service,departure_arrival_time_convenient,ease_of_online_booking,gate_location,food_and_drink,online_boarding,seat_comfort,inflight_entertainment,on_board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,gender_Female,gender_Male,type_of_travel_business_travel,type_of_travel_personal_travel
21232,1,0.487179,1.0,0.180533,0.6,0.6,0.6,0.6,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,0.8,0.0,0.0,1.0,0.0,1.0,0.0

In [12]:
X_test_s.shape

(2589, 24)

In [13]:
#y_test
y_test = pd.read_csv('y_test.csv')
y_test = np.ravel(y_test)
y_test_s = y_test[X_test_s.index]
y_test_s.shape

(2589,)

# 1.0 Avaliação KNN

## 1.1 Dados de treino

In [33]:
# Instanciando
param = np.arange(1,11, 1)
for p in param:
    model = KNeighborsClassifier(n_neighbors=p).fit(X_train_s,y_train_s)
    #predict
    yhat = model.predict(X_train_s)

    # metricas
    acc = round(mt.accuracy_score(y_train_s, yhat),3)
    pr = round(mt.precision_score(y_train_s,yhat),3)
    rc = round(mt.recall_score(y_train_s,yhat),3)
    f1 = round(mt.f1_score(y_train_s,yhat),3)

    print(f'Valor n_neighbor: {p}')
    print(f'Métricas. Acuracia: {acc}, Precision: {pr}, Recall: {rc}, F1_score: {f1}')
    print('=========================================')

Valor n_neighbor: 1
Métricas. Acuracia: 1.0, Precision: 1.0, Recall: 1.0, F1_score: 1.0
=========================================
Valor n_neighbor: 2
Métricas. Acuracia: 0.934, Precision: 1.0, Recall: 0.848, F1_score: 0.918
=========================================
Valor n_neighbor: 3
Métricas. Acuracia: 0.947, Precision: 0.971, Recall: 0.905, F1_score: 0.937
=========================================
Valor n_neighbor: 4
Métricas. Acuracia: 0.927, Precision: 0.983, Recall: 0.847, F1_score: 0.91
=========================================
Valor n_neighbor: 5
Métricas. Acuracia: 0.934, Precision: 0.966, Recall: 0.878, F1_score: 0.92
=========================================
Valor n_neighbor: 6
Métricas. Acuracia: 0.922, Precision: 0.977, Recall: 0.839, F1_score: 0.903
=========================================
Valor n_neighbor: 7
Métricas. Acuracia: 0.925, Precision: 0.961, Recall: 0.862, F1_score: 0.909
=========================================
Valor n_neighbor: 8
Métricas. Acuracia: 0.916, Precision: 0.968, Recall: 0.833, F1_score: 0.896
=========================================
Valor n_neighbor: 9
Métricas. Acuracia: 0.92, Precision: 0.957, Recall: 0.854, F1_score: 0.902
=========================================
Valor n_neighbor: 10
Métricas. Acuracia: 0.916, Precision: 0.966, Recall: 0.834, F1_score: 0.895
=========================================

## 1.2 Dados validação

In [35]:
# Instanciando
param = np.arange(1,11, 1)
for p in param:
    model = KNeighborsClassifier(n_neighbors=p).fit(X_train_s,y_train_s)
    #predict
    yhat = model.predict(X_val_s)

    # metricas
    acc = round(mt.accuracy_score(y_val_s, yhat),3)
    pr = round(mt.precision_score(y_val_s,yhat),3)
    rc = round(mt.recall_score(y_val_s,yhat),3)
    f1 = round(mt.f1_score(y_val_s,yhat),3)

    print(f'Valor n_neighbor: {p}')
    print(f'Métricas. Acuracia: {acc}, Precision: {pr}, Recall: {rc}, F1_score: {f1}')
    print('=========================================')

Valor n_neighbor: 1
Métricas. Acuracia: 0.89, Precision: 0.892, Recall: 0.855, F1_score: 0.873
=========================================
Valor n_neighbor: 2
Métricas. Acuracia: 0.886, Precision: 0.965, Recall: 0.771, F1_score: 0.857
=========================================
Valor n_neighbor: 3
Métricas. Acuracia: 0.9, Precision: 0.922, Recall: 0.846, F1_score: 0.882
=========================================
Valor n_neighbor: 4
Métricas. Acuracia: 0.893, Precision: 0.958, Recall: 0.794, F1_score: 0.868
=========================================
Valor n_neighbor: 5
Métricas. Acuracia: 0.901, Precision: 0.936, Recall: 0.834, F1_score: 0.882
=========================================
Valor n_neighbor: 6
Métricas. Acuracia: 0.897, Precision: 0.96, Recall: 0.8, F1_score: 0.873
=========================================
Valor n_neighbor: 7
Métricas. Acuracia: 0.903, Precision: 0.945, Recall: 0.829, F1_score: 0.883
=========================================
Valor n_neighbor: 8
Métricas. Acuracia: 0.896, Precision: 0.955, Recall: 0.804, F1_score: 0.873
=========================================
Valor n_neighbor: 9
Métricas. Acuracia: 0.901, Precision: 0.948, Recall: 0.822, F1_score: 0.881
=========================================
Valor n_neighbor: 10
Métricas. Acuracia: 0.898, Precision: 0.955, Recall: 0.807, F1_score: 0.875
=========================================

## 1.3 Dados de teste

In [39]:
p=7
model = KNeighborsClassifier(n_neighbors=p).fit(X_train_s,y_train_s)
#predict
yhat = model.predict(X_test_s)

# metricas
acc = round(mt.accuracy_score(y_test_s, yhat),3)
pr = round(mt.precision_score(y_test_s,yhat),3)
rc = round(mt.recall_score(y_test_s,yhat),3)
f1 = round(mt.f1_score(y_test_s,yhat),3)

print(f'Valor n_neighbor: {p}')
print(f'Métricas. Acuracia: {acc}, Precision: {pr}, Recall: {rc}, F1_score: {f1}')
print('=========================================')

Valor n_neighbor: 7
Métricas. Acuracia: 0.903, Precision: 0.942, Recall: 0.836, F1_score: 0.886
=========================================

# 2.0 Avaliação Decision tree

## 2.1 Dados de treino

In [17]:
param = np.arange(2, 11, 1)
metricas = []
for p in param:
    
    model = tr.DecisionTreeClassifier(max_depth=p).fit(X_train_s, y_train_s)
    yhat = model.predict(X_train_s)
    #metricas
    acc = round(mt.accuracy_score(y_train_s, yhat),3)
    pr = round(mt.precision_score(y_train_s,yhat),3)
    rc = round(mt.recall_score(y_train_s,yhat),3)
    f1 = round(mt.f1_score(y_train_s,yhat),3)
    m_value = {'max_depth': p, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
    metricas.append(m_value)

r = pd.DataFrame(metricas)
r

   max_depth  acuracia  precision  recall  f1_score
0          2     0.855      0.858   0.798     0.827
1          3     0.881      0.840   0.894     0.866
2          4     0.890      0.882   0.860     0.871
3          5     0.904      0.931   0.841     0.883
4          6     0.922      0.921   0.896     0.908
5          7     0.934      0.936   0.910     0.923
6          8     0.946      0.953   0.922     0.937
7          9     0.957      0.959   0.940     0.949
8         10     0.970      0.975   0.954     0.965

## 2.2 Dados de validação

In [19]:
param = np.arange(2, 16, 1)
metricas = []
for p in param:
    
    model = tr.DecisionTreeClassifier(max_depth=p).fit(X_train_s, y_train_s)
    yhat = model.predict(X_val_s)
    #metricas
    acc = round(mt.accuracy_score(y_val_s, yhat),3)
    pr = round(mt.precision_score(y_val_s,yhat),3)
    rc = round(mt.recall_score(y_val_s,yhat),3)
    f1 = round(mt.f1_score(y_val_s,yhat),3)
    m_value = {'max_depth': p, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
    metricas.append(m_value)

r = pd.DataFrame(metricas)
r

    max_depth  acuracia  precision  recall  f1_score
0           2     0.862      0.865   0.816     0.840
1           3     0.883      0.843   0.903     0.872
2           4     0.890      0.878   0.873     0.876
3           5     0.901      0.918   0.853     0.884
4           6     0.922      0.915   0.909     0.912
5           7     0.926      0.919   0.914     0.917
6           8     0.925      0.919   0.912     0.916
7           9     0.929      0.919   0.920     0.920
8          10     0.930      0.920   0.922     0.921
9          11     0.926      0.912   0.922     0.917
10         12     0.929      0.916   0.925     0.920
11         13     0.927      0.912   0.923     0.918
12         14     0.926      0.908   0.927     0.918
13         15     0.927      0.912   0.923     0.918

## 2.3 Dados de teste

In [20]:

metricas = []
p=10
    
model = tr.DecisionTreeClassifier(max_depth=p).fit(X_train_s, y_train_s)
yhat = model.predict(X_test_s)
#metricas
acc = round(mt.accuracy_score(y_test_s, yhat),3)
pr = round(mt.precision_score(y_test_s,yhat),3)
rc = round(mt.recall_score(y_test_s,yhat),3)
f1 = round(mt.f1_score(y_test_s,yhat),3)
m_value = {'max_depth': p, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
metricas.append(m_value)

r = pd.DataFrame(metricas)
r

   max_depth  acuracia  precision  recall  f1_score
0         10     0.932      0.927    0.92     0.924

# 3.0 Avaliação Random forest

## 3.1 Dados de treino

In [16]:
#e = 100
#d = 10
metricas = []
estimators = np.arange(10, 101, 10)
depth = np.arange(5, 16, 1)
for e in estimators:
    for d in depth:
        
        model = en.RandomForestClassifier(n_estimators = e, max_depth = d).fit(X_train_s, y_train_s)
        yhat = model.predict(X_train_s)
        
        acc = round(mt.accuracy_score(y_train_s, yhat),3)
        pr = round(mt.precision_score(y_train_s,yhat),3)
        rc = round(mt.recall_score(y_train_s,yhat),3)
        f1 = round(mt.f1_score(y_train_s,yhat),3)

        m_value = {'n_estimators': e ,'max_depth': d, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
        metricas.append(m_value)
m = pd.DataFrame(metricas)
m

     n_estimators  max_depth  acuracia  precision  recall  f1_score
0              10          5     0.906      0.913   0.865     0.888
1              10          6     0.924      0.928   0.893     0.910
2              10          7     0.933      0.929   0.914     0.921
3              10          8     0.946      0.946   0.928     0.937
4              10          9     0.953      0.952   0.938     0.945
..            ...        ...       ...        ...     ...       ...
105           100         11     0.978      0.984   0.965     0.974
106           100         12     0.987      0.992   0.978     0.985
107           100         13     0.993      0.996   0.988     0.992
108           100         14     0.995      0.997   0.992     0.995
109           100         15     0.997      0.999   0.995     0.997

[110 rows x 6 columns]

In [17]:
m.sort_values(by=['acuracia', 'f1_score'], ascending=False)

     n_estimators  max_depth  acuracia  precision  recall  f1_score
76             70         15     0.998      0.999   0.995     0.997
98             90         15     0.997      0.999   0.995     0.997
109           100         15     0.997      0.999   0.995     0.997
21             20         15     0.997      0.998   0.995     0.996
54             50         15     0.997      0.999   0.993     0.996
..            ...        ...       ...        ...     ...       ...
99            100          5     0.918      0.917   0.892     0.904
88             90          5     0.916      0.918   0.884     0.901
22             30          5     0.915      0.923   0.877     0.900
11             20          5     0.913      0.912   0.885     0.898
0              10          5     0.906      0.913   0.865     0.888

[110 rows x 6 columns]

## 3.2 Dados de validação

In [18]:
metricas = []
estimators = np.arange(10, 101, 10)
depth = np.arange(5, 16, 1)
for e in estimators:
    for d in depth:
        
        model = en.RandomForestClassifier(n_estimators = e, max_depth = d).fit(X_train_s, y_train_s)
        yhat = model.predict(X_val_s)
        
        acc = round(mt.accuracy_score(y_val_s, yhat),3)
        pr = round(mt.precision_score(y_val_s,yhat),3)
        rc = round(mt.recall_score(y_val_s,yhat),3)
        f1 = round(mt.f1_score(y_val_s,yhat),3)

        m_value = {'n_estimators': e ,'max_depth': d, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
        metricas.append(m_value)
m = pd.DataFrame(metricas)
m.sort_values(by=['acuracia', 'f1_score'], ascending=False)

     n_estimators  max_depth  acuracia  precision  recall  f1_score
87             80         15     0.947      0.947   0.932     0.939
76             70         15     0.946      0.950   0.927     0.938
98             90         15     0.946      0.948   0.929     0.938
109           100         15     0.945      0.949   0.927     0.938
43             40         15     0.945      0.947   0.927     0.937
..            ...        ...       ...        ...     ...       ...
66             70          5     0.915      0.923   0.882     0.902
11             20          5     0.913      0.916   0.886     0.901
44             50          5     0.911      0.919   0.875     0.897
33             40          5     0.910      0.914   0.880     0.897
0              10          5     0.909      0.922   0.868     0.894

[110 rows x 6 columns]

## 3.3 Dados teste

In [20]:
metricas=[]
e=80
d=15
model = en.RandomForestClassifier(n_estimators = 80, max_depth = 15).fit(X_train_s, y_train_s)
yhat = model.predict(X_test_s)

acc = round(mt.accuracy_score(y_test_s, yhat),3)
pr = round(mt.precision_score(y_test_s,yhat),3)
rc = round(mt.recall_score(y_test_s,yhat),3)
f1 = round(mt.f1_score(y_test_s,yhat),3)

m_value = {'n_estimators': e ,'max_depth': d, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
metricas.append(m_value)
m = pd.DataFrame(metricas)
m.sort_values(by=['acuracia', 'f1_score'], ascending=False)

   n_estimators  max_depth  acuracia  precision  recall  f1_score
0            80         15     0.944      0.948   0.925     0.937

# 4.0 Logistic Regression

## 4.1 Dados de treino

In [15]:
C = np.arange(0.1, 1, 0.4)
solvers = ['lbfgs', 'newton-cg', 'newton-cholesky', 'sag']
max_iters = np.arange(90, 111, 10)
metricas=[]

for c in C:
    for s in solvers:
        for i in max_iters:
            
            model = lm.LogisticRegression(C = c, solver = s, max_iter = i).fit(X_train_s, y_train_s)
            yhat= model.predict(X_train_s)
            
            acc = round(mt.accuracy_score(y_train_s, yhat),3)
            pr = round(mt.precision_score(y_train_s,yhat),3)
            rc = round(mt.recall_score(y_train_s,yhat),3)
            f1 = round(mt.f1_score(y_train_s,yhat),3)
    
            m_value = {'C': c ,'solver': s, 'max_iter': i, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
            metricas.append(m_value)
m = pd.DataFrame(metricas)
m.sort_values(by=['acuracia', 'f1_score'], ascending=False)

      C           solver  max_iter  acuracia  precision  recall  f1_score
0   0.1            lbfgs        90     0.871      0.870   0.825     0.847
1   0.1            lbfgs       100     0.871      0.870   0.825     0.847
2   0.1            lbfgs       110     0.871      0.870   0.825     0.847
3   0.1        newton-cg        90     0.871      0.871   0.825     0.847
4   0.1        newton-cg       100     0.871      0.871   0.825     0.847
5   0.1        newton-cg       110     0.871      0.871   0.825     0.847
6   0.1  newton-cholesky        90     0.871      0.870   0.825     0.847
7   0.1  newton-cholesky       100     0.871      0.870   0.825     0.847
8   0.1  newton-cholesky       110     0.871      0.870   0.825     0.847
9   0.1              sag        90     0.871      0.870   0.825     0.847
10  0.1              sag       100     0.871      0.870   0.825     0.847
11  0.1              sag       110     0.871      0.870   0.825     0.847
15  0.5        newton-cg        90     0.871      0.869   0.826     0.847
16  0.5        newton-cg       100     0.871      0.869   0.826     0.847
17  0.5        newton-cg       110     0.871      0.869   0.826     0.847
18  0.5  newton-cholesky        90     0.871      0.869   0.826     0.847
19  0.5  newton-cholesky       100     0.871      0.869   0.826     0.847
20  0.5  newton-cholesky       110     0.871      0.869   0.826     0.847
21  0.5              sag        90     0.871      0.869   0.826     0.847
22  0.5              sag       100     0.871      0.869   0.826     0.847
23  0.5              sag       110     0.871      0.869   0.826     0.847
24  0.9            lbfgs        90     0.871      0.868   0.826     0.847
25  0.9            lbfgs       100     0.871      0.868   0.826     0.847
26  0.9            lbfgs       110     0.871      0.868   0.826     0.847
27  0.9        newton-cg        90     0.871      0.868   0.826     0.847
28  0.9        newton-cg       100     0.871      0.868   0.826     0.847
29  0.9        newton-cg       110     0.871      0.868   0.826     0.847
30  0.9  newton-cholesky        90     0.871      0.868   0.826     0.847
31  0.9  newton-cholesky       100     0.871      0.868   0.826     0.847
32  0.9  newton-cholesky       110     0.871      0.868   0.826     0.847
33  0.9              sag        90     0.871      0.868   0.826     0.847
34  0.9              sag       100     0.871      0.868   0.826     0.847
35  0.9              sag       110     0.871      0.868   0.826     0.847
12  0.5            lbfgs        90     0.870      0.869   0.825     0.846
13  0.5            lbfgs       100     0.870      0.869   0.825     0.846
14  0.5            lbfgs       110     0.870      0.869   0.825     0.846

## 4.2 Dados de validação

In [21]:
C = np.arange(0.1, 1, 0.4)
solvers = ['lbfgs', 'newton-cg', 'newton-cholesky', 'sag']
max_iters = np.arange(90, 111, 10)
metricas=[]

for c in C:
    for s in solvers:
        for i in max_iters:
            
            model = lm.LogisticRegression(C = c, solver = s, max_iter = i).fit(X_train_s, y_train_s)
            yhat= model.predict(X_val_s)
            
            acc = round(mt.accuracy_score(y_val_s, yhat),3)
            pr = round(mt.precision_score(y_val_s,yhat),3)
            rc = round(mt.recall_score(y_val_s,yhat),3)
            f1 = round(mt.f1_score(y_val_s,yhat),3)
    
            m_value = {'C': c ,'solver': s, 'max_iter': i, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
            metricas.append(m_value)
m = pd.DataFrame(metricas)
m.sort_values(by=['acuracia', 'f1_score'], ascending=False)

      C           solver  max_iter  acuracia  precision  recall  f1_score
12  0.5            lbfgs        90     0.870      0.868   0.833     0.850
13  0.5            lbfgs       100     0.870      0.868   0.833     0.850
14  0.5            lbfgs       110     0.870      0.868   0.833     0.850
15  0.5        newton-cg        90     0.870      0.868   0.833     0.850
16  0.5        newton-cg       100     0.870      0.868   0.833     0.850
17  0.5        newton-cg       110     0.870      0.868   0.833     0.850
18  0.5  newton-cholesky        90     0.870      0.868   0.833     0.850
19  0.5  newton-cholesky       100     0.870      0.868   0.833     0.850
20  0.5  newton-cholesky       110     0.870      0.868   0.833     0.850
21  0.5              sag        90     0.870      0.868   0.833     0.850
22  0.5              sag       100     0.870      0.868   0.833     0.850
23  0.5              sag       110     0.870      0.868   0.833     0.850
24  0.9            lbfgs        90     0.869      0.867   0.833     0.850
25  0.9            lbfgs       100     0.869      0.867   0.833     0.850
26  0.9            lbfgs       110     0.869      0.867   0.833     0.850
27  0.9        newton-cg        90     0.869      0.867   0.833     0.850
28  0.9        newton-cg       100     0.869      0.867   0.833     0.850
29  0.9        newton-cg       110     0.869      0.867   0.833     0.850
30  0.9  newton-cholesky        90     0.869      0.867   0.833     0.850
31  0.9  newton-cholesky       100     0.869      0.867   0.833     0.850
32  0.9  newton-cholesky       110     0.869      0.867   0.833     0.850
33  0.9              sag        90     0.869      0.867   0.833     0.850
34  0.9              sag       100     0.869      0.867   0.833     0.850
35  0.9              sag       110     0.869      0.867   0.833     0.850
0   0.1            lbfgs        90     0.869      0.869   0.830     0.849
1   0.1            lbfgs       100     0.869      0.869   0.830     0.849
2   0.1            lbfgs       110     0.869      0.869   0.830     0.849
3   0.1        newton-cg        90     0.869      0.869   0.831     0.849
4   0.1        newton-cg       100     0.869      0.869   0.831     0.849
5   0.1        newton-cg       110     0.869      0.869   0.831     0.849
6   0.1  newton-cholesky        90     0.869      0.869   0.830     0.849
7   0.1  newton-cholesky       100     0.869      0.869   0.830     0.849
8   0.1  newton-cholesky       110     0.869      0.869   0.830     0.849
9   0.1              sag        90     0.869      0.869   0.830     0.849
10  0.1              sag       100     0.869      0.869   0.830     0.849
11  0.1              sag       110     0.869      0.869   0.830     0.849

## 4.3 Dados de teste

In [22]:
c=0.5
s='lbfgs'
i=90
metricas=[]


            
model = lm.LogisticRegression(C = c, solver = s, max_iter = i).fit(X_train_s, y_train_s)
yhat= model.predict(X_test_s)

acc = round(mt.accuracy_score(y_test_s, yhat),3)
pr = round(mt.precision_score(y_test_s,yhat),3)
rc = round(mt.recall_score(y_test_s,yhat),3)
f1 = round(mt.f1_score(y_test_s,yhat),3)

m_value = {'C': c ,'solver': s, 'max_iter': i, 'acuracia': acc, 'precision': pr, 'recall': rc, 'f1_score': f1 }
metricas.append(m_value)
m = pd.DataFrame(metricas)
m.sort_values(by=['acuracia', 'f1_score'], ascending=False)

     C solver  max_iter  acuracia  precision  recall  f1_score
0  0.5  lbfgs        90      0.87      0.871   0.834     0.852