# 0.0 Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn import cluster as c
from sklearn import metrics as mt

## 0.1 Load dataset

In [2]:
X = pd.read_csv('X_dataset.csv')
print(X.shape)
X.head()

(178, 13)

,alcohol,malic_acid,ash,ash_alcanity,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280,proline
0,1.518613,0.191700,0.232053,-1.169593,1.913905,0.627586,0.573840,-0.659563,1.224884,0.251717,0.455285,0.970696,0.561341
1,0.246290,0.205534,-0.827996,-2.490847,0.018145,0.575862,0.510549,-0.820719,-0.544721,-0.293321,0.463415,0.780220,0.550642
2,0.196879,0.320158,1.109334,-0.268738,0.088358,0.627586,0.611814,-0.498407,2.135968,0.269020,0.447154,0.695971,0.646933
3,1.691550,0.239130,0.487926,-0.809251,0.930918,0.989655,0.664557,-0.981875,1.032155,1.186068,0.308943,0.798535,0.857347
4,0.295700,0.365613,1.840403,0.451946,1.281985,0.627586,0.495781,0.226796,0.401404,-0.319276,0.455285,0.608059,0.325963

## 1.0 Kmeans

In [8]:
clusters = np.arange(2, 11, 1)
metricas = []

for n in clusters:
    model = c.KMeans(n_clusters = n)
    labels = model.fit_predict(X)
    #metricas
    ss = round( mt.silhouette_score(X, labels), 3)
    m_value = {'n_clusters': n, 'Silhouette_Score': ss}
    metricas.append(m_value)

m = pd.DataFrame(metricas)
m.sort_values(by='Silhouette_Score', ascending=False)

   n_clusters  Silhouette_Score
1           3             0.233
2           4             0.230
0           2             0.213
3           5             0.211
4           6             0.207
6           8             0.207
8          10             0.188
7           9             0.161
5           7             0.157

## 2.0 Affinity Propagation

In [6]:
#pref = np.arange(-100, -40, 1)
p = -50
damping = [0.6, 0.7, 0.8, 0.9]
metricas = []

for d in damping:
    model = c.AffinityPropagation(preference = p, damping = d, max_iter = 500 )
    model.fit(X)
    
    labels = model.predict(X)
    #metricas
    ss = round( mt.silhouette_score(X, labels), 3)
    n = len(np.unique(labels))
    m_value = {'preference': p, 'damping': d, 'n_clusters': n, 'Silhouette_Score': ss}
    metricas.append(m_value) 

m = pd.DataFrame(metricas)
m.sort_values(by='Silhouette_Score', ascending=False)

   preference  damping  n_clusters  Silhouette_Score
0         -50      0.6           6             0.184
1         -50      0.7           6             0.173
2         -50      0.8           6             0.173
3         -50      0.9           6             0.165